var lyrics = [
  { text: "Saat engkau tertidur" },
  { text: "Aku pergi menghibur" },
  { text: "Beda kota, pisah raga, bukan masalahku" },
  { text: "Lihat wajahmu di layar, ku tetap bersyukur" },
  { text: "Saat engkau terjaga" },
  { text: "Aku 'kan ada di sana" },
  { text: "Sempatkan bermain dan bawakan cendera mata" },
  { text: "Satu sampai lima tahun, cepat tak terasa" },
  { text: "Segala hal kuupayakan untuk melindungi" },
  { text: "Tunggu aku kembali lagi esok pagi" },
  { text: "Tumbuh lebih baik, cari panggilanmu" },
  { text: "Jadi lebih baik dibanding diriku" },
  { text: "'Tuk sementara ini aku mengembara jauh" },
  { text: "Saat dewasa kau 'kan mengerti" },
  { text: "Saat engkau dewasa" },
  { text: "Dan aku kian menua" },
  { text: "Jika ku berpulang lebih awal, tidak apa" },
  { text: "Berjumpa lagi di sana, aku tetap sama" },
  { text: "Saat engkau teringat" },
  { text: "Tengkar kita, manakala" },
  { text: "Maaf atas perjalanan yang tidak sempurna" },
  { text: "Namun percayalah, untukmu kujual dunia" },
  { text: "Segala hal kuupayakan untuk melindungi (untuk melindungi)" },
  { text: "Tunggu aku kembali lagi esok pagi (selalu janjiku pada dirimu)" },
  { text: "Tumbuh lebih baik, cari panggilanmu" },
  { text: "Jadi lebih baik dibanding diriku" },
  { text: "Dan tertawalah saat ini selepas-lepasnya" },
  { text: "Kar'na kelak kau 'kan tersakiti" },
  { text: "Aku tahu kamu hebat" },
  { text: "Namun, s'lamanya diriku pasti berkutat" },
  { text: "'Tuk s'lalu jauhkanmu dari dunia yang jahat" },
  { text: "Ini sumpahku padamu 'tuk biarkanmu" },
  { text: "Tumbuh lebih baik, cari panggilanmu" },
  { text: "Jadi lebih baik dibanding diriku" },
  { text: "'Tuk sementara kita tertawakan berbagai hal" },
  { text: "Yang lucu dan lara selepas lepasnya" },
  { text: "Saat dewasa kau 'kan mengerti" },
  { text: "Kar'na kelak kau 'kan tersakiti" },
  { text: "Saat dewasa kau 'kan mengerti" },
  { text: "Kar'na kelak kau 'kan tersakiti" }
];