var lyrics = [
  { time: 20.0, text: "Saat engkau tertidur" },
  { time: 26.0, text: "Aku pergi menghibur" },
  { time: 31.0, text: "Beda kota, pisah raga, bukan masalahku" },
  { time: 37.0, text: "Lihat wajahmu di layar, ku tetap bersyukur" },
  { time: 42.0, text: "Saat engkau terjaga" },
  { time: 48.0, text: "Aku 'kan ada di sana" },
  { time: 52.0, text: "Sempatkan bermain dan bawakan cenderamata" },
  { time: 58.0, text: "Satu sampai lima tahun, cepat tak terasa" },
  { time: 64.0, text: "Segala hal kuupayakan untuk melindungi" },
  { time: 74.0, text: "Tunggu aku kembali lagi esok pagi" },
  { time: 85.0, text: "Tumbuh lebih baik, cari panggilanmu" },
  { time: 90.0, text: "Jadi lebih baik dibanding diriku" },
  { time: 96.0, text: "'Tuk sementara ini aku mengembara jauh" },
  { time: 108.0, text: "Saat dewasa kau 'kan mengerti" },

  { time: 122.0, text: "Saat engkau dewasa" },
  { time: 127.0, text: "Dan aku kian menua" },
  { time: 133.0, text: "Jika ku berpulang lebih awal, tidak apa" },
  { time: 138.0, text: "Berjumpa lagi di sana, aku tetap sama" },
  { time: 144.0, text: "Saat engkau teringat" },
  { time: 149.0, text: "Tengkar kita, manakala" },
  { time: 155.0, text: "Maaf atas perjalanan yang tidak sempurna" },
  { time: 165.0, text: "Namun percayalah, untukmu kujual dunia" },
  { time: 176.0, text: "Segala hal kuupayakan untuk melindungi (untuk melindungi)" },
  { time: 181.0, text: "Tunggu aku kembali lagi esok pagi (selalu janjiku pada dirimu)" },
  { time: 187.0, text: "Tumbuh lebih baik, cari panggilanmu" },
  { time: 192.0, text: "Jadi lebih baik dibanding diriku" }
];