var lyrics = [
  { time: 20.0, text: "Saat engkau tertidur" },
  { time: 26.0, text: "Aku pergi menghibur" },
  { time: 31.0, text: "Beda kota, pisah raga, bukan masalahku" },
  { time: 37.0, text: "Lihat wajahmu di layar, ku tetap bersyukur" },
  { time: 42.0, text: "Saat engkau terjaga" },
  { time: 48.0, text: "Aku 'kan ada di sana" },
  { time: 52.0, text: "Sempatkan bermain dan bawakan cenderamata" },
  { time: 58.0, text: "Satu sampai lima tahun, cepat tak terasa" },
  { time: 64.0, text: "Segala hal kuupayakan untuk melindungi" },
  { time: 74.0, text: "Tunggu aku kembali lagi esok pagi" },
  { time: 85.0, text: "Tumbuh lebih baik, cari panggilanmu" },
  { time: 90.0, text: "Jadi lebih baik dibanding diriku" },
  { time: 96.0, text: "'Tuk sementara ini aku mengembara jauh" },
  { time: 108.0, text: "Saat dewasa kau 'kan mengerti" },
  { time: 122.0, text: "Saat engkau dewasa" },
  { time: 127.0, text: "Dan aku kian menua" },
  { time: 133.0, text: "Jika ku berpulang lebih awal, tidak apa" },
  { time: 138.0, text: "Berjumpa lagi di sana, aku tetap sama" },
  { time: 144.0, text: "Saat engkau teringat" },
  { time: 149.0, text: "Tengkar kita, manakala" },
  { time: 155.0, text: "Maaf atas perjalanan yang tidak sempurna" },
  { time: 159.0, text: "Namun percayalah, untukmu kujual dunia" },
  { time: 164.0, text: "Segala hal kuupayakan untuk melindungi (untuk melindungi)" },
  { time: 175.0, text: "Tunggu aku kembali lagi esok pagi (selalu janjiku pada dirimu)" },
  { time: 186.0, text: "Tumbuh lebih baik dari panggilanmu" },
  { time: 192.0, text: "Jadi lebih baik,di Banding diriku" },
  { time: 197.0, text: "Dan tertawalah saat ini selepas-lepasnya" },
  { time: 209.0, text: "Kar'na kelak kau 'kan tersakiti" },
  { time: 215.0, text: "Aku tahu kamu hebat" },
  { time: 218.0, text: "Namun, s'lamanya diriku pasti berkutat" },
  { time: 223.0, text: "'Tuk s'lalu jauhkanmu dari dunia yang jahat" },
  { time: 226.0, text: "Ini sumpahku padamu 'tuk biarkanmu" },
  { time: 231.0, text: "Tumbuh lebih baik, cari panggilanmu" },
  { time: 236.0, text: "Jadi lebih baik dibanding diriku" },
  { time: 241.0, text: "'Tuk sementara kita tertawakan berbagai hal" },
  { time: 249.0, text: "Yang lucu dan lara selepas lepasnya" },
  { time: 254.0, text: "Saat dewasa kau 'kan mengerti" },
  { time: 259.0, text: "Kar'na kelak kau 'kan tersakiti" },
  { time: 265.0, text: "Saat dewasa kau 'kan mengerti" },
  { time: 270.0, text: "Kar'na kelak kau 'kan tersakiti" }
];