var lyrics = [
  { time: 0.0, text: "Oh jelas aku tahu, bunga akan layu" },
  { time: 5.0, text: "Rumput kian mengering, daun kan menguning" },
  { time: 10.0, text: "Kau tahu menurutku waktu adalah" },
  { time: 14.5, text: "Kutukan, ancaman, bualan" },
  { time: 20.0, text: "Dan satu per satu orang sekitarku" },
  { time: 25.0, text: "Mulai ditinggalkan, oh ini peringatan" },
  { time: 30.0, text: "Untukku, o Tuan, wahai Kematian" },
  { time: 35.0, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 40.0, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 45.0, text: "Namun jangan hari ini" },
  { time: 50.0, text: "Melihatmu masuk ke dalam ruang operasi" },
  { time: 55.0, text: "Berdoa semalam suntuk di kamar yang hening" },
  { time: 60.0, text: "Tanpa metafora dan analogi" },
  { time: 65.0, text: "Kiasan berbelit diksi, tanpa berbungkus fiksi" },
  { time: 70.0, text: "Aku takut" },
  { time: 75.0, text: "Untuknya, o Tuan, wahai Kematian" },
  { time: 80.0, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 85.0, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 90.0, text: "Namun jangan hari ini" },
  { time: 95.0, text: "Kurelakan, o Tuan" },
  { time: 100.0, text: "Kurelakan, namun jangan hari ini" },
  { time: 105.0, text: "Kurelakan, o Tuan" },
  { time: 110.0, text: "Kurelakan, namun jangan hari ini" },
  { time: 115.0, text: "Kurelakan, o Tuan" },
  { time: 120.0, text: "Kurelakan, namun jangan hari ini" },
  { time: 125.0, text: "Namun jangan hari ini" }
];