var lyrics = [
  { time: 303.3, text: "Oh jelas aku tahu, bunga akan layu" },
  { time: 308.3, text: "Rumput kian mengering, daun kan menguning" },
  { time: 313.1, text: "Kau tahu menurutku waktu adalah" },
  { time: 317.6, text: "Kutukan, ancaman, bualan" },
  { time: 322.1, text: "Dan satu per satu orang sekitarku" },
  { time: 327.4, text: "Mulai ditinggalkan, oh ini peringatan" },
  { time: 331.7, text: "Untukku, o Tuan, wahai Kematian" },
  { time: 336.0, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 340.2, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 344.2, text: "Namun jangan hari ini" },
  { time: 348.0, text: "Melihatmu masuk ke dalam ruang operasi" },
  { time: 352.6, text: "Berdoa semalam suntuk di kamar yang hening" },
  { time: 357.1, text: "Tanpa metafora dan analogi" },
  { time: 361.4, text: "Kiasan berbelit diksi, tanpa berbungkus fiksi" },
  { time: 365.3, text: "Aku takut" },
  { time: 368.4, text: "Untuknya, o Tuan, wahai Kematian" },
  { time: 372.5, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 376.5, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 380.4, text: "Namun jangan hari ini" },
  { time: 383.9, text: "Kurelakan, o Tuan" },
  { time: 386.8, text: "Kurelakan, namun jangan hari ini" },
  { time: 390.3, text: "Kurelakan, o Tuan" },
  { time: 393.1, text: "Kurelakan, namun jangan hari ini" },
  { time: 396.2, text: "Kurelakan, o Tuan" },
  { time: 399.0, text: "Kurelakan, namun jangan hari ini" },
  { time: 402.3, text: "Namun jangan hari ini" }
];