var lyrics = [
  { time: 34.5, text: "Oh jelas aku tahu, bunga akan layu" },
  { time: 41.7, text: "Rumput kian mengering, daun kan menguning" },
  { time: 48.9, text: "Kau tahu menurutku waktu adalah" },
  { time: 56.1, text: "Kutukan, ancaman, bualan" },
  { time: 63.3, text: "Dan satu per satu orang sekitarku" },
  { time: 70.5, text: "Mulai ditinggalkan, oh ini peringatan" },
  { time: 77.7, text: "Untukku, o Tuan, wahai Kematian" },
  { time: 84.9, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 92.1, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 99.3, text: "Namun jangan hari ini" },
  { time: 106.5, text: "Melihatmu masuk ke dalam ruang operasi" },
  { time: 113.7, text: "Berdoa semalam suntuk di kamar yang hening" },
  { time: 120.9, text: "Tanpa metafora dan analogi" },
  { time: 128.1, text: "Kiasan berbelit diksi, tanpa berbungkus fiksi" },
  { time: 135.3, text: "Aku takut" },
  { time: 142.5, text: "Untuknya, o Tuan, wahai Kematian" },
  { time: 149.7, text: "Ku tak bisa melawan jamah perhentian" },
  { time: 156.9, text: "Berjanji kuikhlaskan dengan rela" },
  { time: 164.1, text: "Namun jangan hari ini" },
  { time: 171.3, text: "Kurelakan, o Tuan" },
  { time: 178.5, text: "Kurelakan, namun jangan hari ini" },
  { time: 185.7, text: "Kurelakan, o Tuan" },
  { time: 192.9, text: "Kurelakan, namun jangan hari ini" },
  { time: 200.1, text: "Kurelakan, o Tuan" },
  { time: 207.3, text: "Kurelakan, namun jangan hari ini" },
  { time: 214.5, text: "Namun jangan hari ini" },
  { time: 221.7, text: "Hembus nafas terakhir kau tarik perlahan" },
  { time: 228.9, text: "Kupeluk tubuhmu dan kuucap selamat jalan" },
  { time: 236.1, text: "Air mataku tumpah tak tertahankan" },
  { time: 243.3, text: "Namun kuikhlaskan" },
  { time: 250.5, text: "Kurelakan, o Tuan" },
  { time: 257.7, text: "Tak akan ku lawan keputusan Tuhan" },
  { time: 264.9, text: "Kini ku berdiri sendiri" },
  { time: 272.1, text: "Namun dengan hati yang mengerti" },
  { time: 279.3, text: "Bahwa cinta sejati abadi" },
  { time: 286.5, text: "Meski raga tak lagi di sisi" }
];