var lyrics = [
  { time: 32.0, text: "Nama yang sama bertahan" },
  { time: 37.0, text: "Dalam ruangan hening" },
  { time: 41.0, text: "Tanpa suara bertahan" },
  { time: 45.0, text: "Tak bergeming" },
  { time: 49.0, text: "Terlalu lama bercanda" },
  { time: 54.0, text: "Kita tak terbiasa" },
  { time: 57.0, text: "Dengan celaka yang nyata" },
  { time: 62.0, text: "Diam tak berdaya" },
  { time: 66.0, text: "Namun aku bingung kenapa ku tak pergi" },
  { time: 70.0, text: "Aku bingung kalian masih di sini" },
  { time: 74.0, text: "Apa mungkin karena terlalu lama" },
  { time: 78.0, text: "Apa benar tuk berbagi derita" },
  { time: 82.0, text: "Mungkin nanti semua justru memburuk" },
  { time: 87.0, text: "Hati-hati namun terjatuh lagi" },
  { time: 92.0, text: "Tapi luka adalah niscaya" },
  { time: 97.0, text: "Kutanggung denganmu selama ku mampu" },
  { time: 103.0, text: "Selama ku mampu" },
  { time: 117.0, text: "Di kehidupan kedua (di kesempatan kedua)" },
  { time: 120.0, text: "S'moga kau tak terlalu keras kepala" },
  { time: 125.0, text: "Atau mungkin ini bukan yang pertama (ini bukan yang pertama)" },
  { time: 129.0, text: "Dan kita diberi kesempatan berubah" },
  { time: 133.0, text: "Kuyakin nyawa kita bertautan" },
  { time: 138.0, text: "Khatam berbagai cobaan" },
  { time: 142.0, text: "Selalu menertawakan ramalan bintang kartu tarot" },
  { time: 147.0, text: "Orang pintar pembaca nasib" },
  { time: 150.0, text: "Namun aku bingung kenapa ku tak pergi" },
  { time: 155.0, text: "Aku bingung kalian masih di sini" },
  { time: 159.0, text: "Apa mungkin karena terlalu lama" },
  { time: 163.0, text: "Apa benar tuk berbagi derita" },
  { time: 167.0, text: "Mungkin nanti semua justru memburuk" },
  { time: 171.0, text: "Hati-hati namun terjatuh lagi" },
  { time: 176.0, text: "Tapi luka adalah niscaya" },
  { time: 180.0, text: "Kutanggung denganmu selama ku mampu" },
  { time: 187.0, text: "Selama ku mampu" },
  { time: 192.0, text: "Selalu menertawakan ramalan bintang kartu tarot" },
  { time: 197.0, text: "Orang pintar pembaca nasib namun" },
  { time: 202.0, text: "Padamu kupercaya" },
  { time: 211.0, text: "Tak masuk logika" },
  { time: 219.0, text: "Padamu kupercaya" },
  { time: 227.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 236.0, text: "Padamu kupercaya (padamu kupercaya)" },
  { time: 244.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 252.0, text: "Padamu kupercaya (padamu kupercaya)" },
  { time: 261.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 269.0, text: "Padamu kupercaya" },
  { time: 278.0, text: "Tak masuk logika" }
]