var lyrics = [
  { time: 32.0, text: "Nama yang sama bertahan" },
  { time: 37.0, text: "Dalam ruangan hening" },
  { time: 41.0, text: "Tanpa suara bertahan" },
  { time: 45.0, text: "Tak bergeming" },
  { time: 49.0, text: "Terlalu lama bercanda" },
  { time: 54.0, text: "Kita tak terbiasa" },
  { time: 57.0, text: "Dengan celaka yang nyata" },
  { time: 62.0, text: "Diam tak berdaya" },
  { time: 66.0, text: "Namun aku bingung kenapa ku tak pergi" },
  { time: 70.0, text: "Aku bingung kalian masih di sini" },
  { time: 74.0, text: "Apa mungkin karena terlalu lama" },
  { time: 78.0, text: "Apa benar tuk berbagi derita" },
  { time: 82.0, text: "Mungkin nanti semua justru memburuk" },
  { time: 87.0, text: "Hati-hati namun terjatuh lagi" },
  { time: 92.0, text: "Tapi luka adalah niscaya" },
  { time: 97.0, text: "Kutanggung denganmu selama ku mampu" },
  { time: 102.0, text: "Selama ku mampu" },
  { time: 106.0, text: "Di kehidupan kedua (di kesempatan kedua)" },
  { time: 110.0, text: "S'moga kau tak terlalu keras kepala" },
  { time: 112.0, text: "Atau mungkin ini bukan yang pertama (ini bukan yang pertama)" },
  { time: 116.0, text: "Dan kita diberi kesempatan berubah" },
  { time: 119.0, text: "Kuyakin nyawa kita bertautan" },
  { time: 124.0, text: "Khatam berbagai cobaan" },
  { time: 126.0, text: "Selalu menertawakan ramalan bintang kartu tarot" },
  { time: 128.0, text: "Orang pintar pembaca nasib" },
  { time: 132.0, text: "Namun aku bingung kenapa ku tak pergi" },
  { time: 137.0, text: "Aku bingung kalian masih di sini" },
  { time: 143.0, text: "Apa mungkin karena terlalu lama" },
  { time: 158.0, text: "Apa benar tuk berbagi derita" },
  { time: 160.0, text: "Mungkin nanti semua justru memburuk" },
  { time: 165.0, text: "Hati-hati namun terjatuh lagi" },
  { time: 169.0, text: "Tapi luka adalah niscaya" },
  { time: 174.0, text: "Kutanggung denganmu selama ku mampu" },
  { time: 179.0, text: "Selama ku mampu" },
  { time: 185.0, text: "Selalu menertawakan ramalan bintang kartu tarot" },
  { time: 188.0, text: "Orang pintar pembaca nasib namun" },
  { time: 192.0, text: "Padamu kupercaya" },
  { time: 197.0, text: "Tak masuk logika" },
  { time: 202.0, text: "Padamu kupercaya" },
  { time: 208.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 212.0, text: "Padamu kupercaya (padamu kupercaya)" },
  { time: 217.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 222.0, text: "Padamu kupercaya (padamu kupercaya)" },
  { time: 230.0, text: "Tak masuk logika (tak masuk logika)" },
  { time: 237.0, text: "Padamu kupercaya" },
  { time: 242.0, text: "Tak masuk logika" }
]