var lyrics = [
  { time: 27, text: "Kau bermasalah jiwa aku pun rada gila" },
  { time: 30, text: "Jodoh akal-akalan neraka kita bersama" },
  { time: 33, text: "Kau langganan menangis lakimu muntah-muntah" },
  { time: 36, text: "Begitu terus sampai Iblis tobat dan sedekah" },
  { time: 39, text: "Terkadang rasanya leher terbakar hingga pagi" },
  { time: 43, text: "Seperti aku hidup berpasangan dengan api" },
  { time: 46, text: "Berhenti ulangi psikolog dan terapi" },
  { time: 49, text: "Aku isi bensin kita coba lagi" },
  { time: 52, text: "Tapi sbelumnya sejuta sayang untukmu cinta" },
  { time: 59, text: "Karna aku pun bola panas juga kadang lebih atau sama parahnya" },
  { time: 65, text: "Dan jika bicara tentang masa depan aku pun bingung tak punya tebakan" },
  { time: 71, text: "Lagu cinta untuk akhir dunia lihat kami nyanyikan ini bersama" },
  { time: 77, text: "Smoga hidup kita trus begini-gini saja" },
  { time: 85, text: "Walau sungai meluap dan kurs tak masuk logika" },
  { time: 91, text: "Smoga kita mencintai apa adanya" },
  { time: 97, text: "Walau katanya skarang ku bisa masuk penjara" },
  { time: 103, text: "Satu per satu hari per hari" },
  { time: 110, text: "Yang menyakiti benahi lagi" },
  { time: 116, text: "Perihal esok tuk nanti dulu" },
  { time: 122, text: "Perihal cincin kucari waktu" },
  { time: 128, text: "Persetan kata siapa mau bilang apa tak guna" },
  { time: 134, text: "Mreka hanya tahu namamu mreka takkan jadi diriku" },
  { time: 141, text: "Persetan aturan cinta tak tertulis di atas batu" },
  { time: 147, text: "Apa kau ingin menjadi benar atau ingin menjadi muda?" },
  { time: 152, text: "Smoga hidup kita trus begini-gini saja" },
  { time: 159, text: "Walau sungai meluap dan kurs tak masuk logika" },
  { time: 165, text: "Smoga kita mencintai apa adanya" },
  { time: 171, text: "Walau katanya skarang ku bisa masuk penjara" },
  { time: 178, text: "Persetan kata siapa mau bilang apa tak guna" },
  { time: 184, text: "Mreka hanya tahu namamu mreka takkan jadi diriku" },
  { time: 190, text: "Persetan aturan cinta tak tertulis di atas batu" },
  { time: 196, text: "Apa kau ingin menjadi benar atau kau ingin menjadi muda" },
  { time: 203, text: "Lagu cinta untuk akhir dunia" },
  { time: 209, text: "Sekarang bantu aku nyanyikan ini bersama" },
  { time: 213, text: "Smoga hidup kita trus begini-gini saja" },
  { time: 221, text: "Walau sungai meluap dan kurs tak masuk logika" },
  { time: 227, text: "Smoga kita mencintai apa adanya" },
  { time: 234, text: "Walau katanya skarang ku bisa masuk penjara" },
  { time: 240, text: "Satu per satu hari per hari" },
  { time: 247, text: "Yang menyakiti benahi lagi" },
  { time: 252, text: "Perihal esok tuk nanti dulu" },
  { time: 259, text: "Perihal cincin kucari waktu" },
];