const lirikEvaluasi = [
  { time: 0.0, text: "Yang tak bisa terobati" },
  { time: 8.0, text: "Biarlah mengering sendiri" },
  { time: 17.0, text: "Menghias tubuh dan" },
  { time: 23.0, text: "Yang mengevaluasi ragamu" },
  { time: 29.0, text: "Hanya kau sendiri" },
  { time: 32.0, text: "Mereka tak mampu" },
  { time: 36.0, text: "Melewati yang telah kaulewa-" },
  { time: 40.0, text: "Tiap berganti ha-" },
  { time: 42.0, text: "Rintangan yang kauhadapi" },
  { time: 48.0, text: "Masalah yang mengeruh" },
  { time: 52.0, text: "Oh, perasaan yang rapuh" },
  { time: 59.0, text: "Ini belum separuhnya" },
  { time: 64.0, text: "Biasa saja, kamu tak apa" },
  { time: 74.0, text: "Yang selalu ingin ambil peran" },
  { time: 80.0, text: "Hanya berlomba menjadi lebih" },
  { time: 85.0, text: "Sedih dari diri" },
  { time: 88.0, text: "Muak dikesampingkan, disamakan" },
  { time: 91.0, text: "Hatimu terluka sempurna" },
  { time: 93.0, text: "Masalah yang mengeruh" },
  { time: 96.0, text: "Oh, perasaan yang rapuh" },
  { time: 100.0, text: "Ini belum separuhnya" },
  { time: 105.0, text: "Biasa saja, kamu tak apa" },
  { time: 112.0, text: "Perjalanan yang jauh" },
  { time: 117.0, text: "Kau bangun untuk bertaruh" },
  { time: 121.0, text: "Hari belum selesai" },
  { time: 124.0, text: "Biasa saja, kamu tak apa" },
  { time: 130.0, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 137.0, text: "Tidur sejenak, menemui esok pagi" },
  { time: 144.0, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 151.0, text: "Ku masih ingin melihatmu esok hari" },
  { time: 158.0, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 165.0, text: "Tidur sejenak, menemui esok pagi" },
  { time: 172.0, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 179.0, text: "Ku masih ingin melihatmu esok hari" },
  { time: 186.0, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 193.0, text: "Tidur sejenak, menemui esok pagi" },
  { time: 200.0, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 207.0, text: "Ku masih ingin melihatmu esok hari" }
];