var lyrics = [
  { time: 1, text: "Yang tak bisa terobati" },
  { time: 1, text: "Biarlah mengering sendiri" },
  { time: 1, text: "Menghias tubuh dan" },
  { time: 1, text: "Yang mengevaluasi ragamu" },
  { time: 1, text: "Hanya kau sendiri" },
  { time: 1, text: "Mereka tak mampu" },
  { time: 1, text: "Melewati yang telah kaulewa-" },
  { time: 1, text: "Tiap berganti ha-" },
  { time: 1, text: "Rintangan yang kauhadapi" },
  { time: 1, text: "Masalah yang mengeruh" },
  { time: 1, text: "Oh, perasaan yang rapuh" },
  { time: 1, text: "Ini belum separuhnya" },
  { time: 1, text: "Biasa saja, kamu tak apa" },
  { time: 1, text: "Yang selalu ingin ambil peran" },
  { time: 1, text: "Hanya berlomba menjadi lebih" },
  { time: 1, text: "Sedih dari diri" },
  { time: 1, text: "Muak dikesampingkan, disamakan" },
  { time: 1, text: "Hatimu terluka sempurna" },
  { time: 1, text: "Masalah yang mengeruh" },
  { time: 1, text: "Oh, perasaan yang rapuh" },
  { time: 1, text: "Ini belum separuhnya" },
  { time: 1, text: "Biasa saja, kamu tak apa" },
  { time: 1, text: "Perjalanan yang jauh" },
  { time: 1, text: "Kau bangun untuk bertaruh" },
  { time: 1, text: "Hari belum selesai" },
  { time: 1, text: "Biasa saja, kamu tak apa" },
  { time: 1, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 1, text: "Tidur sejenak, menemui esok pagi" },
  { time: 1, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 1, text: "Ku masih ingin melihatmu esok hari" },
  { time: 1, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 1, text: "Tidur sejenak, menemui esok pagi" },
  { time: 1, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 1, text: "Ku masih ingin melihatmu esok hari" },
  { time: 1, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 1, text: "Tidur sejenak, menemui esok pagi" },
  { time: 1, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 1, text: "Ku masih ingin melihatmu esok hari" }
];