var lyrics = [
  { time: 0.00, text: "Yang tak bisa terobati" },
  { time: 8.00, text: "Biarlah mengering sendiri" },
  { time: 16.00, text: "Menghias tubuh dan" },
  { time: 19.00, text: "Yang mengevaluasi ragamu" },
  { time: 31.00, text: "Hanya kau sendiri" },
  { time: 35.00, text: "Mereka tak mampu" },
  { time: 37.00, text: "Melewati yang telah kaulewa- Tiap berganti ha- Rintangan yang kauhadapi" },
  { time: 48.00, text: "Masalah yang mengeruh" },
  { time: 52.00, text: "Oh, perasaan yang rapuh" },
  { time: 59.00, text: "Ini belum separuhnya" },
  { time: 64.00, text: "Biasa saja, kamu tak apa" },
  { time: 74.00, text: "Yang selalu ingin ambil peran" },
  { time: 80.00, text: "Hanya berlomba menjadi lebih" },
  { time: 85.00, text: "Sedih dari diri" },
  { time: 88.00, text: "Muak dikesampingkan, disamakan" },
  { time: 91.00, text: "Hatimu terluka sempurna" },
  { time: 93.00, text: "Masalah yang mengeruh" },
  { time: 96.00, text: "Oh, perasaan yang rapuh" },
  { time: 100.00, text: "Ini belum separuhnya" },
  { time: 105.00, text: "Biasa saja, kamu tak apa" },
  { time: 112.00, text: "Perjalanan yang jauh" },
  { time: 117.00, text: "Kau bangun untuk bertaruh" },
  { time: 121.00, text: "Hari belum selesai" },
  { time: 124.00, text: "Biasa saja, kamu tak apa" },
  { time: 130.00, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 137.00, text: "Tidur sejenak, menemui esok pagi" },
  { time: 144.00, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 151.00, text: "Ku masih ingin melihatmu esok hari" },
  { time: 158.00, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 165.00, text: "Tidur sejenak, menemui esok pagi" },
  { time: 172.00, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 179.00, text: "Ku masih ingin melihatmu esok hari" },
  { time: 186.00, text: "Bilas muka, gosok gigi, evaluasi" },
  { time: 193.00, text: "Tidur sejenak, menemui esok pagi" },
  { time: 200.00, text: "Walau pedih, ku bersamamu kali ini" },
  { time: 207.00, text: "Ku masih ingin melihatmu esok hari" }
];