var lyrics = [
  { time: 12, text: "Wajahmu ku ingat selalu lupakan" },
  { time: 22, text: "Hal-hal yang menggangguku" },
  { time: 26, text: "Karena hari ini mata kita beradu" },
  { time: 32, text: "Kita saling bantu melepas perasaan" },
  { time: 38, text: "Tinggi ke angkasa menantang dunia" },
  { time: 44, text: "Merayakan muda tuk satu jam saja" },
  { time: 49, text: "Kita hampir mati dan kau selamatkan aku" },
  { time: 55, text: "Dan ku menyelamatkanmu dan sekarang aku tahu" },
  { time: 61, text: "Cerita kita tak jauh berbeda" },
  { time: 69, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 74, text: "Namun suratmu kan ku ceritakan ke anak-anakku nanti." },
  { time: 79, text: "Bahwa aku pernah dicintai with everything u are" },
  { time: 90, text: "Fully as I am with everything u are" },
  { time: 98, text: "Wajahmu yang beragam rupa pastikan" },
  { time: 108, text: "Ku tak sendirian." },
  { time: 112, text: "Jalani derita kau bawakan kisahmu" },
  { time: 118, text: "Aku mendengarkan oh kita bergantian" },
  { time: 124, text: "Bertukar nestapa menawar trauma" },
  { time: 130, text: "Datang seadanya terasku terbuka" },
  { time: 135, text: "Kita hampir mati dan kau sеlamatkan aku" },
  { time: 141, text: "Dan ku menyelamatkanmu dan sekarang aku tahu" },
  { time: 147, text: "Cеrita kita tak jauh berbeda" },
  { time: 155, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 160, text: "Namun suratmu kan kuceritakan ke anak-anakku nanti" },
  { time: 165, text: "Bahwa aku pernah dicintai" },
  { time: 170, text: "Seada-adanya sekurang-kurangnya" },
  { time: 176, text: "Walau sulit utarakan hatiku dengan indah" },
  { time: 183, text: "Walau jarang ku bernyanyi dengan cara yang indah" },
  { time: 189, text: "Tapi tak sekali pun kisahku pernah kau bantah hu" },
  { time: 196, text: "Cerita kita tak jauh berbeda." },
  { time: 204, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 209, text: "Namun suratmu kan ku ceritakan ke anak-anakku nanti" },
  { time: 215, text: "Bahwa aku pernah dicintai with everything u are" },
  { time: 226, text: "Fully as I am with everything u are" },
];