var lyrics = [
  { time: 2.1, text: "Wajahmu ku ingat selalu lupakan" },
  { time: 5.2, text: "Hal-hal yang menggangguku" },
  { time: 7.9, text: "Karena hari ini mata kita beradu" },
  { time: 10.9, text: "Kita saling bantu melepas perasaan" },
  { time: 13.9, text: "Tinggi ke angkasa menantang dunia" },
  { time: 17.5, text: "Merayakan muda tuk satu jam saja" },
  { time: 20.9, text: "Kita hampir mati dan kau selamatkan aku" },
  { time: 24.3, text: "Dan ku menyelamatkanmu dan sekarang aku tahu" },
  { time: 28.2, text: "Cerita kita tak jauh berbeda" },
  { time: 31.5, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 35.8, text: "Namun suratmu kan ku ceritakan ke anak-anakku nanti" },
  { time: 40.5, text: "Bahwa aku pernah dicintai with everything u are" },
  { time: 44.5, text: "Fully as I am with everything u are" },
  { time: 48.7, text: "Wajahmu yang beragam rupa pastikan" },
  { time: 52.8, text: "Ku tak sendirian" },
  { time: 55.4, text: "Jalani derita kau bawakan kisahmu" },
  { time: 58.7, text: "Aku mendengarkan oh kita bergantian" },
  { time: 62.4, text: "Bertukar nestapa menawar trauma" },
  { time: 66.0, text: "Datang seadanya terasku terbuka" },
  { time: 69.4, text: "Kita hampir mati dan kau selamatkan aku" },
  { time: 72.9, text: "Dan ku menyelamatkanmu dan sekarang aku tahu" },
  { time: 76.8, text: "Cerita kita tak jauh berbeda" },
  { time: 80.2, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 84.4, text: "Namun suratmu kan kuceritakan ke anak-anakku nanti" },
  { time: 89.2, text: "Bahwa aku pernah dicintai" },
  { time: 92.4, text: "Seada-adanya sekurang-kurangnya" },
  { time: 96.0, text: "Walau sulit utarakan hatiku dengan indah" },
  { time: 99.4, text: "Walau jarang ku bernyanyi dengan cara yang indah" },
  { time: 102.7, text: "Tapi tak sekali pun kisahku pernah kau bantah hu" },
  { time: 106.3, text: "Cerita kita tak jauh berbeda" },
  { time: 109.8, text: "Got beat down by the world sometimes I wanna fold" },
  { time: 114.1, text: "Namun suratmu kan ku ceritakan ke anak-anakku nanti" },
  { time: 118.8, text: "Bahwa aku pernah dicintai with everything u are" },
  { time: 123.1, text: "Fully as I am with everything u are" },
];
