var lyrics = [
  { time: "0.10", text: "Rayakan hari ini" },
  { time: "0.20", text: "Besok sisa sengsara" },
  { time: "0.30", text: "Belum pulan kau pun di sini" },
  { time: "0.40", text: "Temani diriku" },
  { time: "0.50", text: "Kita bersandiwara" },
  { time: "0.60", text: "Bicara tak semestinya" },
  { time: "0.70", text: "Walau kita tahu nyatanya" },
  { time: "0.80", text: "Semua tak baik saja" },
  { time: "0.90", text: "Ada masanya kita" },
  { time: "1.00", text: "Mencuri ruang dan waktu" },
  { time: "1.10", text: "Walau pasti berlalu" },
  { time: "1.20", text: "Biarkan saja kita ke sana" },
  { time: "1.30", text: "Selagi masih bisa bersama" },
  { time: "1.40", text: "Bersama" },
  { time: "1.50", text: "Semuanya sementara" },
  { time: "1.60", text: "Kita di ujung cerita" },
  { time: "1.70", text: "Untuk lima menit coba kau" },
  { time: "1.80", text: "Mengambil alih dunia" },
  { time: "1.90", text: "Ada masanya kita" },
  { time: "2.00", text: "Mencuri ruang dan waktu" },
  { time: "2.10", text: "Walau pasti berlalu" },
  { time: "2.20", text: "Biarkan saja kita ke sana" },
  { time: "2.30", text: "Selagi masih bisa bersama" },
  { time: "2.40", text: "Ada masanya kita" },
  { time: "2.50", text: "Mencuri ruang dan waktu" },
  { time: "2.60", text: "Walau pasti berlalu" },
  { time: "2.70", text: "Biarkan saja kita ke sana (kita ke sana)" },
  { time: "2.80", text: "Selama-lamanya (selama-lamanya)" },
  { time: "2.90", text: "Selagi masih bisa bersama" },
  { time: "3.00", text: "Bersama oh" },
  { time: "3.10", text: "Bersama" },
  { time: "3.20", text: "Bersama oh oh" }
];