var lyrics = [
  { time: "0.0", text: "Rayakan hari ini" },
  { time: "0.1", text: "Besok sisa sengsara" },
  { time: "0.2", text: "Belum pulan kau pun di sini" },
  { time: "0.3", text: "Temani diriku" },
  { time: "0.4", text: "Kita bersandiwara" },
  { time: "0.5", text: "Bicara tak semestinya" },
  { time: "0.6", text: "Walau kita tahu nyatanya" },
  { time: "0.7", text: "Semua tak baik saja" },
  { time: "0.8", text: "Ada masanya kita" },
  { time: "0.9", text: "Mencuri ruang dan waktu" },
  { time: "1.0", text: "Walau pasti berlalu" },
  { time: "1.1", text: "Biarkan saja kita ke sana" },
  { time: "1.2", text: "Selagi masih bisa bersama" },
  { time: "1.3", text: "Bersama" },
  { time: "1.4", text: "Semuanya sementara" },
  { time: "1.5", text: "Kita di ujung cerita" },
  { time: "1.6", text: "Untuk lima menit coba kau" },
  { time: "1.7", text: "Mengambil alih dunia" },
  { time: "1.8", text: "Ada masanya kita" },
  { time: "1.9", text: "Mencuri ruang dan waktu" },
  { time: "2.0", text: "Walau pasti berlalu" },
  { time: "2.1", text: "Biarkan saja kita ke sana" },
  { time: "2.2", text: "Selagi masih bisa bersama" },
  { time: "2.3", text: "Ada masanya kita" },
  { time: "2.4", text: "Mencuri ruang dan waktu" },
  { time: "2.5", text: "Walau pasti berlalu" },
  { time: "2.6", text: "Biarkan saja kita ke sana (kita ke sana)" },
  { time: "2.7", text: "Selama-lamanya (selama-lamanya)" },
  { time: "2.8", text: "Selagi masih bisa bersama" },
  { time: "2.9", text: "Bersama oh" },
  { time: "3.0", text: "Bersama" },
  { time: "3.1", text: "Bersama oh oh" }
];