var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 35, text: "Rayakan hari ini" },
  { time: 40, text: "Besok sisa sengsara" },
  { time: 44, text: "Belum pulan kau pun di sini" },
  { time: 50, text: "Temani diriku" },
  { time: 61, text: "Kita bersandiwara" },
  { time: 65, text: "Bicara tak semestinya" },
  { time: 70, text: "Walau kita tahu nyatanya" },
  { time: 76, text: "Semua tak baik saja" },
  { time: 80, text: "Ada masanya kita" },
  { time: 88, text: "Mencuri ruang dan waktu" },
  { time: 95, text: "Walau pasti berlalu" },
  { time: 102, text: "Biarkan saja kita ke sana" },
  { time: 108, text: "Selagi masih bisa bersama" },
  { time: 116, text: "Bersama" },
  { time: 130, text: "Semuanya sementara" },
  { time: 134, text: "Kita di ujung cerita" },
  { time: 139, text: "Untuk lima menit coba kau" },
  { time: 144, text: "Mengambil alih dunia" },
  { time: 148, text: "Ada masanya kita" },
  { time: 156, text: "Mencuri ruang dan waktu" },
  { time: 163, text: "Walau pasti berlalu" },
  { time: 170, text: "Biarkan saja kita ke sana" },
  { time: 176, text: "Selagi masih bisa bersama" },
  { time: 219, text: "Ada masanya kita" },
  { time: 228, text: "Mencuri ruang dan waktu" },
  { time: 234, text: "Walau pasti berlalu" },
  { time: 241, text: "Biarkan saja kita ke sana (kita ke sana)" },
  { time: 248, text: "Selama-lamanya (selama-lamanya)" },
  { time: 252, text: "Selagi masih bisa bersama" },
  { time: 260, text: "Bersama oh" },
  { time: 264, text: "Bersama" },
  { time: 268, text: "Bersama oh oh" }
];