var lyrics = [
  { time: 3, text: "Aku ingin jadi teman nyamanmu" },
  { time: 9, text: "Tempat kauhilangkan keluh kesahmu" },
  { time: 14, text: "Kita berbincang tak karuan tanpa beban" },
  { time: 20, text: "Dan juga khayalan tentang masa depan" },
  { time: 27, text: "Ku tak ingin cepat berlalu (berlalu)" },
  { time: 34, text: "Waktu yang kupunya denganmu" },
  { time: 38, text: "Kita berdansa dan tertawa, gandeng tangan" },
  { time: 44, text: "Semoga bergema sampai selamanya" },
  { time: 51, text: "Dunia pasti ada akhirnya" },
  { time: 57, text: "Bintang-bintang pun ada umurnya" },
  { time: 63, text: "Maka tenang saja, kita di sini berdua" },
  { time: 72, text: "Nikmati sementara yang ada" },
  { time: 87, text: "Bersandar padaku, taruh di bahuku" },
  { time: 93, text: "Relakan semua, bebas semaumu (bebas semaumu)" },
  { time: 98, text: "Percayalah (percayalah), ini sayang terlewatkan (terlewatkan)" },
  { time: 104, text: "Kusampaikan dalam nyanyian, bergema sampai slamanya" },
  { time: 135, text: "Dunia pasti ada akhirnya" },
  { time: 141, text: "Bintang-bintang pun ada umurnya" },
  { time: 146, text: "Maka tenang saja, kita di sini berdua" },
  { time: 156, text: "Nikmati sementara yang ada" },
  { time: 165, text: "Bintang-bintang pun ada umurnya" },
  { time: 171, text: "Maka tenang saja, kita di sini berdua" },
  { time: 180, text: "Nikmati sementara yang ada" },
  { time: 186, text: "Semoga bergema selamanya" },
];