var lyrics = [
  { time: 13, text: "Tak sadar ku temukan" },
  { time: 18, text: "Temukan wanita rupawan yang sadarkan" },
  { time: 24, text: "Dia seorang tiada lain tiada bukan" },
  { time: 29, text: "Hanya dia" },
  { time: 38, text: "Dia buatku nyaman" },
  { time: 44, text: "Dalam hangat pelukan" },
  { time: 48, text: "Dia perasa yang mengerti yang kurasa" },
  { time: 53, text: "Hanya dia" },
  { time: 60, text: "Kan ku arungi tujuh laut samudra" },
  { time: 67, text: "Kan ku daki pegunungan himalaya" },
  { time: 72, text: "Apapun kan ku lakukan tuk dirimu sayang" },
  { time: 78, text: "Oh penjaga hati" },
  { time: 93, text: "Kau dan aku sempurna" },
  { time: 98, text: "Semoga ada cara tuk terus bersama" },
  { time: 103, text: "Selalu ku tunggu" },
  { time: 106, text: "Tak mau berlalu" },
  { time: 109, text: "Kau dan aku" },
  { time: 116, text: "Kan ku arungi tujuh laut samudra" },
  { time: 122, text: "Kan ku daki pegunungan himalaya" },
  { time: 128, text: "Apapun kan ku lakukan tuk dirimu sayang" },
  { time: 133, text: "Oh penjaga hatiku" },
  { time: 140, text: "Oh oh" },
  { time: 165, text: "Kan ku arungi tujuh laut samudra" },
  { time: 171, text: "Kan ku daki pegunungan himalaya" },
  { time: 178, text: "Apapun kan ku lakukan tuk dirimu sayang" },
  { time: 182, text: "Oh penjaga hatiku oh" },
  { time: 189, text: "Karna bersamamu semua terasa indah" },
  { time: 196, text: "Gundah gulana hatiku pun hancur sirna" },
  { time: 202, text: "Janji ku tak kan ku lepas wahai kau bidadariku dari surga" },
  { time: 210, text: "Tuk selamanya." },
  { time: 217, text: "Tuk selamanya" },
  { time: 222, text: "Tuk selamanya" },
];